name: boilerplateapp
description: Flutter Boilerplate app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_displaymode: ^0.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.5.5
  hive: ^2.2.3
  hydrated_bloc: ^9.1.0
  intl: ^0.17.0
  ionicons: ^0.2.2
  local_database:
    path: packages/local_database
  logger: ^1.2.2
  path_provider: ^2.0.13
  rest_client:
    path: packages/rest_client
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  mockito: ^5.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    remove_alpha_ios: false
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    # Optional
    integrations:
      flutter_svg: true
      flare_flutter: true
      rive: true
      lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
